# Generated by Django 3.2.5 on 2022-08-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
